# Generated by Django 5.0.6 on 2024-05-09 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envelope', '0002_envelope_balance_envelope_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_description', models.CharField(max_length=100)),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('envelope', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='envelope.envelope')),
            ],
        ),
    ]
