# Generated by Django 5.0.6 on 2024-05-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expense_description',
            new_name='category',
        ),
    ]
